import{Product} from '../../shared/product.model';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'AirPods',
    price: 1200,
    rate: 4,
    stock: 5,
    image: 'airpods-1.jpg',
    brand: 'Apple',
    category: 'Wireless Earbuds',
    color: 'White',
    warranty: '1 Year',
    description:
      'Lightweight wireless earbuds with clear sound, stable connection, and comfortable fit for daily use.',
    features: ['Bluetooth 5.0', 'Touch controls', 'Charging case', 'Mic for calls'],
  },
  {
    id: 2,
    name: 'AirPods Pro',
    price: 1800,
    rate: 5,
    stock: 0,
    image: 'airpods-2.jpg',
    brand: 'Apple',
    category: 'Wireless Earbuds',
    color: 'White',
    warranty: '1 Year',
    description:
      'Premium earbuds with improved sound quality and a better seal for noise isolation and richer bass.',
    features: ['Better bass', 'Noise isolation', 'Charging case', 'Dual microphones'],
  },
  {
    id: 3,
    name: 'Earbuds Black',
    price: 600,
    rate: 3,
    stock: 10,
    image: 'earbuds-1.jpg',
    brand: 'SoundBeat',
    category: 'Wireless Earbuds',
    color: 'Black',
    warranty: '6 Months',
    description:
      'Budget-friendly earbuds with decent audio quality and a compact charging case.',
    features: ['Compact case', 'Good battery', 'Lightweight', 'Built-in mic'],
  },
  {
    id: 4,
    name: 'Earbuds White',
    price: 650,
    rate: 4,
    stock: 0,
    image: 'earbuds-2.jpg',
    brand: 'SoundBeat',
    category: 'Wireless Earbuds',
    color: 'White',
    warranty: '6 Months',
    description:
      'Comfortable earbuds with balanced sound and stable pairing for everyday listening.',
    features: ['Balanced sound', 'Fast pairing', 'Charging case', 'Mic for calls'],
  },
  {
    id: 5,
    name: 'Headset Black',
    price: 900,
    rate: 4,
    stock: 3,
    image: 'headset-1.jpg',
    brand: 'StudioX',
    category: 'Headphones',
    color: 'Black',
    warranty: '1 Year',
    description:
      'Over-ear headset with comfortable cushions and clear sound for music and gaming.',
    features: ['Over-ear', 'Comfort cushions', 'Noise reduction', 'Strong bass'],
  },
  {
    id: 6,
    name: 'Headset Gray',
    price: 950,
    rate: 5,
    stock: 7,
    image: 'headset-2.jpg',
    brand: 'StudioX',
    category: 'Headphones',
    color: 'Gray',
    warranty: '1 Year',
    description:
      'High-quality headset with rich audio, comfortable fit, and durable build.',
    features: ['Premium audio', 'Comfort fit', 'Durable build', 'Wide soundstage'],
  },
  {
    id: 7,
    name: 'Red Headphones',
    price: 1100,
    rate: 5,
    stock: 2,
    image: 'red-headphones-1.jpg',
    brand: 'BeatWave',
    category: 'Headphones',
    color: 'Red',
    warranty: '1 Year',
    description:
      'Stylish red headphones with powerful bass and crisp highs for an energetic sound.',
    features: ['Powerful bass', 'Clear highs', 'Adjustable headband', 'Foldable design'],
  },
  {
    id: 8,
    name: 'Red Headphones Plus',
    price: 1300,
    rate: 4,
    stock: 0,
    image: 'red-headphones-2.jpg',
    brand: 'BeatWave',
    category: 'Headphones',
    color: 'Red',
    warranty: '1 Year',
    description:
      'Enhanced version with improved comfort and stronger sound tuning for long sessions.',
    features: ['Extra comfort', 'Enhanced bass', 'Soft cushions', 'Durable hinges'],
  },
  {
    id: 9,
    name: 'Smart Phone',
    price: 12000,
    rate: 5,
    stock: 4,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=60',
    brand: 'NovaTech',
    category: 'Smartphones',
    description:
      'Modern smartphone with a sharp display, strong performance, and a capable camera system.',
    features: ['AMOLED display', 'Fast charging', 'Multi-lens camera', '5G support'],
  },
  {
    id: 10,
    name: 'Laptop',
    price: 25000,
    rate: 4,
    stock: 3,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=60',
    brand: 'WorkPro',
    category: 'Laptops',
    description:
      'Reliable laptop for study and work with good battery life and smooth performance.',
    features: ['SSD storage', 'Long battery', 'Full HD display', 'Lightweight body'],
  },
  {
    id: 11,
    name: 'Smart Watch',
    price: 3200,
    rate: 4,
    stock: 8,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=60',
    brand: 'FitPulse',
    category: 'Wearables',
    description:
      'Smart watch that tracks your activity, heart rate, and notifications throughout the day.',
    features: ['Heart rate', 'Step tracking', 'Sleep monitor', 'Notifications'],
  },
  {
    id: 12,
    name: 'Digital Camera',
    price: 9000,
    rate: 4,
    stock: 6,
    image: 'https://images.unsplash.com/photo-1519183071298-a2962be96c0b?auto=format&fit=crop&w=900&q=60',
    brand: 'CamX',
    category: 'Cameras',
    description:
      'Compact camera with clear photos and easy controls, suitable for travel and daily shots.',
    features: ['High resolution', 'Optical zoom', 'Stabilization', 'HD video'],
  },
  {
    id: 13,
    name: 'Wireless Mouse',
    price: 450,
    rate: 4,
    stock: 12,
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=60',
    brand: 'ClickPro',
    category: 'Accessories',
    description:
      'Comfortable wireless mouse with smooth tracking and long-lasting battery.',
    features: ['Ergonomic', 'Smooth tracking', 'Battery efficient', 'Wireless USB receiver'],
  },
];
